/**
 * Contract examples data (auto-generated).
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Generated from api/examples/contracts/*.json
 * Run: npm run generate:examples
 */

export const contractExamplesData = [
  {
    "id": "admin.me.admin",
    "method": "GET",
    "path": "/admin/me",
    "status": 200,
    "request_model": null,
    "response_model": "UserRead",
    "request": null,
    "response": {
      "id": 2,
      "username": "admin@example.com",
      "school_ids": [],
      "school_names": [],
      "is_active": true,
      "is_admin": true
    }
  },
  {
    "id": "admin.me.no-schools",
    "method": "GET",
    "path": "/admin/me",
    "status": 200,
    "request_model": null,
    "response_model": "UserRead",
    "request": null,
    "response": {
      "id": 3,
      "username": "noaccess@example.com",
      "school_ids": [],
      "school_names": [],
      "is_active": true,
      "is_admin": false
    }
  },
  {
    "id": "admin.me.user",
    "method": "GET",
    "path": "/admin/me",
    "status": 200,
    "request_model": null,
    "response_model": "UserRead",
    "request": null,
    "response": {
      "id": 1,
      "username": "user@example.com",
      "school_ids": [
        1
      ],
      "school_names": [
        "Focus School Academy"
      ],
      "is_active": true,
      "is_admin": false
    }
  },
  {
    "id": "auth.login.success",
    "method": "POST",
    "path": "/auth/login",
    "status": 200,
    "request_model": null,
    "response_model": "TokenResponse",
    "request": {
      "username": "user@example.com",
      "password": "password123"
    },
    "response": {
      "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2MjQwMDAwfQ.fake_signature",
      "token_type": "bearer"
    }
  },
  {
    "id": "dimensions.dataset",
    "method": "GET",
    "path": "/dimensions",
    "status": 200,
    "request_model": null,
    "response_model": "DimensionsResponse",
    "request": null,
    "response": {
      "school_id": null,
      "variables": [
        {
          "key": "bewell_questionnaire__bw_wbeing_1",
          "raw_key": "bw_wbeing_1",
          "form_id": "bewell_questionnaire"
        },
        {
          "key": "bewell_questionnaire__bw_wbeing_2",
          "raw_key": "bw_wbeing_2",
          "form_id": "bewell_questionnaire"
        },
        {
          "key": "phq9_questionnaire__phq9_1",
          "raw_key": "phq9_1",
          "form_id": "phq9_questionnaire"
        },
        {
          "key": "bewell_questionnaire__bw_wbeing_total",
          "raw_key": "bw_wbeing_total",
          "form_id": "bewell_questionnaire"
        }
      ],
      "dimensions": [
        {
          "key": "class",
          "type": "string"
        },
        {
          "key": "d_age",
          "type": "string"
        },
        {
          "key": "d_city",
          "type": "string"
        },
        {
          "key": "d_country",
          "type": "string"
        },
        {
          "key": "d_ethnicity",
          "type": "string"
        },
        {
          "key": "d_sex",
          "type": "string"
        },
        {
          "key": "yearGroup",
          "type": "string"
        }
      ]
    }
  },
  {
    "id": "dimensions.school",
    "method": "GET",
    "path": "/dimensions?school_id=1",
    "status": 200,
    "request_model": null,
    "response_model": "DimensionsResponse",
    "request": null,
    "response": {
      "school_id": 1,
      "variables": [
        {
          "key": "bewell_questionnaire__bw_wbeing_1",
          "raw_key": "bw_wbeing_1",
          "form_id": "bewell_questionnaire"
        },
        {
          "key": "bewell_questionnaire__bw_wbeing_2",
          "raw_key": "bw_wbeing_2",
          "form_id": "bewell_questionnaire"
        },
        {
          "key": "phq9_questionnaire__phq9_1",
          "raw_key": "phq9_1",
          "form_id": "phq9_questionnaire"
        },
        {
          "key": "bewell_questionnaire__bw_wbeing_total",
          "raw_key": "bw_wbeing_total",
          "form_id": "bewell_questionnaire"
        }
      ],
      "dimensions": [
        {
          "key": "class",
          "type": "string"
        },
        {
          "key": "d_age",
          "type": "string"
        },
        {
          "key": "d_city",
          "type": "string"
        },
        {
          "key": "d_country",
          "type": "string"
        },
        {
          "key": "d_ethnicity",
          "type": "string"
        },
        {
          "key": "d_sex",
          "type": "string"
        },
        {
          "key": "yearGroup",
          "type": "string"
        }
      ]
    }
  },
  {
    "id": "me.anonymous",
    "method": "GET",
    "path": "/me",
    "status": 200,
    "request_model": null,
    "response_model": "MeAnonymous",
    "request": null,
    "response": {
      "kind": "anonymous"
    }
  },
  {
    "id": "me.authenticated.admin",
    "method": "GET",
    "path": "/me",
    "status": 200,
    "request_model": null,
    "response_model": "MeAuthenticated",
    "request": null,
    "response": {
      "kind": "authenticated",
      "id": 2,
      "username": "admin@example.com",
      "is_admin": true,
      "schools": [
        {
          "id": 1,
          "name": "Focus School Academy"
        },
        {
          "id": 2,
          "name": "Neighbouring School"
        }
      ]
    }
  },
  {
    "id": "me.authenticated",
    "method": "GET",
    "path": "/me",
    "status": 200,
    "request_model": null,
    "response_model": "MeAuthenticated",
    "request": null,
    "response": {
      "kind": "authenticated",
      "id": 1,
      "username": "user@example.com",
      "is_admin": false,
      "schools": [
        {
          "id": 1,
          "name": "Focus School Academy"
        }
      ]
    }
  },
  {
    "id": "query.period-based.simple",
    "method": "GET",
    "path": "/query?v=bewell_questionnaire__bw_wbeing_1",
    "status": 200,
    "request_model": null,
    "response_model": "NewQueryResponse",
    "request": null,
    "response": {
      "query": {
        "school_id": null,
        "variables": [
          "bewell_questionnaire__bw_wbeing_1"
        ],
        "dimensions": [],
        "variable_prefixes": []
      },
      "dimensions": [],
      "periods": [
        "2023-2024",
        "2024-2025"
      ],
      "variables": [
        {
        "variable": "bewell_questionnaire__bw_wbeing_1",
        "periods": {
          "2023-2024": {
            "suppressed": false,
            "notes": [
              "values-rescaled"
            ],
            "question_versions": {
              "1": 5,
              "2": 5
            },
            "cells": [
              {
                "mean": 3.5,
                  "n": 10
                }
              ]
            },
            "2024-2025": {
              "suppressed": false,
              "cells": [
                {
                  "mean": 3.8,
                  "n": 12
                }
              ]
            }
          }
        }
      ]
    }
  },
  {
    "id": "query.period-based.with-dimensions",
    "method": "GET",
    "path": "/query?v=bewell_questionnaire__bw_wbeing_1&d=d_sex",
    "status": 200,
    "request_model": null,
    "response_model": "NewQueryResponse",
    "request": null,
    "response": {
      "query": {
        "school_id": null,
        "variables": [
          "bewell_questionnaire__bw_wbeing_1"
        ],
        "dimensions": [
          "d_sex"
        ],
        "variable_prefixes": []
      },
      "dimensions": [
        "d_sex"
      ],
      "periods": [
        "2023-2024"
      ],
      "variables": [
        {
          "variable": "bewell_questionnaire__bw_wbeing_1",
          "periods": {
            "2023-2024": {
              "suppressed": false,
              "cells": [
                {
                  "mean": 3.2,
                  "n": 5,
                  "d_sex": "M"
                },
                {
                  "mean": 3.8,
                  "n": 5,
                  "d_sex": "F"
                }
              ]
            }
          }
        }
      ]
    }
  },
  {
    "id": "schools.admin-all",
    "method": "GET",
    "path": "/schools",
    "status": 200,
    "request_model": null,
    "response_model": "SchoolListResponse",
    "request": null,
    "response": [
      {
        "id": 1,
        "name": "Focus School Academy",
        "size": "medium",
        "category": "comprehensive",
        "geographical_neighbor_ids": [
          2
        ],
        "statistical_neighbor_ids": [
          2,
          3
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1",
            "2"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B",
                "C"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "Black",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "7"
              ],
              "scope": "shared"
            }
          ]
        }
      },
      {
        "id": 2,
        "name": "Neighbouring School",
        "size": "large",
        "category": "academy",
        "geographical_neighbor_ids": [
          1
        ],
        "statistical_neighbor_ids": [
          1,
          3
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B",
                "C"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "Black",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "8"
              ],
              "scope": "shared"
            }
          ]
        }
      },
      {
        "id": 3,
        "name": "State Local High",
        "size": "small",
        "category": "grammar",
        "geographical_neighbor_ids": [],
        "statistical_neighbor_ids": [
          1,
          2
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "7"
              ],
              "scope": "shared"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "schools.empty",
    "method": "GET",
    "path": "/schools",
    "status": 200,
    "request_model": null,
    "response_model": "SchoolListResponse",
    "request": null,
    "response": []
  },
  {
    "id": "schools.user-default",
    "method": "GET",
    "path": "/schools",
    "status": 200,
    "request_model": null,
    "response_model": "SchoolListResponse",
    "request": null,
    "response": [
      {
        "id": 1,
        "name": "Focus School Academy",
        "size": "medium",
        "category": "comprehensive",
        "geographical_neighbor_ids": [
          2
        ],
        "statistical_neighbor_ids": [
          2,
          3
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1",
            "2"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B",
                "C"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "Black",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "7"
              ],
              "scope": "shared"
            }
          ]
        }
      },
      {
        "id": 2,
        "name": "Neighbouring School",
        "size": "large",
        "category": "academy",
        "geographical_neighbor_ids": [
          1
        ],
        "statistical_neighbor_ids": [
          1
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B",
                "C"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "Black",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "8"
              ],
              "scope": "shared"
            }
          ]
        }
      }
    ]
  }
] as const;
