/**
 * Contract examples data (auto-generated).
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Generated from api/examples/contracts/*.json
 * Run: npm run generate:examples
 */

export const contractExamplesData = [
  {
    "id": "admin.me.admin",
    "method": "GET",
    "path": "/admin/me",
    "status": 200,
    "request_model": null,
    "response_model": "UserRead",
    "request": null,
    "response": {
      "id": 2,
      "username": "admin@example.com",
      "school_ids": [],
      "school_names": [],
      "is_active": true,
      "is_admin": true
    }
  },
  {
    "id": "admin.me.no-schools",
    "method": "GET",
    "path": "/admin/me",
    "status": 200,
    "request_model": null,
    "response_model": "UserRead",
    "request": null,
    "response": {
      "id": 3,
      "username": "noaccess@example.com",
      "school_ids": [],
      "school_names": [],
      "is_active": true,
      "is_admin": false
    }
  },
  {
    "id": "admin.me.user",
    "method": "GET",
    "path": "/admin/me",
    "status": 200,
    "request_model": null,
    "response_model": "UserRead",
    "request": null,
    "response": {
      "id": 1,
      "username": "user@example.com",
      "school_ids": [
        1
      ],
      "school_names": [
        "Focus School Academy"
      ],
      "is_active": true,
      "is_admin": false
    }
  },
  {
    "id": "auth.login.success",
    "method": "POST",
    "path": "/auth/login",
    "status": 200,
    "request_model": null,
    "response_model": "TokenResponse",
    "request": {
      "username": "user@example.com",
      "password": "password123"
    },
    "response": {
      "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2MjQwMDAwfQ.fake_signature",
      "token_type": "bearer"
    }
  },
  {
    "id": "query.default",
    "method": "POST",
    "path": "/api/query",
    "status": 200,
    "request_model": "QueryRequest",
    "response_model": "QueryResponse",
    "request": {
      "school_id": 1,
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {},
      "include_neighbors": true
    },
    "response": {
      "focus_school": {
        "school_id": 1,
        "school_name": "Focus School Academy",
        "results": {
          "1": {
            "suppressed": false,
            "suppression_message": null,
            "results": [
              {
                "mean": 75.5,
                "student_n": 120
              }
            ]
          },
          "2": {
            "suppressed": false,
            "suppression_message": null,
            "results": [
              {
                "mean": 78.2,
                "student_n": 125
              }
            ]
          }
        }
      },
      "neighbors": [
        {
          "school_id": 2,
          "school_name": "Neighbouring School",
          "results": {
            "1": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "mean": 72.1,
                  "student_n": 110
                }
              ]
            },
            "2": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "mean": 74.8,
                  "student_n": 115
                }
              ]
            }
          }
        }
      ],
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {}
    }
  },
  {
    "id": "query.error-400",
    "method": "POST",
    "path": "/api/query",
    "status": 400,
    "request_model": "QueryRequest",
    "response_model": "ErrorDetailResponse",
    "request": {
      "school_id": 1,
      "variable": "invalid_variable",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {},
      "include_neighbors": true
    },
    "response": {
      "detail": "Variable 'invalid_variable' not found in dataset"
    }
  },
  {
    "id": "query.error-403",
    "method": "POST",
    "path": "/api/query",
    "status": 403,
    "request_model": "QueryRequest",
    "response_model": "ErrorDetailResponse",
    "request": {
      "school_id": 999,
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {},
      "include_neighbors": true
    },
    "response": {
      "detail": "You do not have permission to access this school"
    }
  },
  {
    "id": "query.error-500",
    "method": "POST",
    "path": "/api/query",
    "status": 500,
    "request_model": "QueryRequest",
    "response_model": "ErrorDetailResponse",
    "request": {
      "school_id": 1,
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {},
      "include_neighbors": true
    },
    "response": {
      "detail": "Internal server error"
    }
  },
  {
    "id": "query.filter-sex-f",
    "method": "POST",
    "path": "/api/query",
    "status": 200,
    "request_model": "QueryRequest",
    "response_model": "QueryResponse",
    "request": {
      "school_id": 1,
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {
        "d_sex": [
          "F"
        ]
      },
      "include_neighbors": true
    },
    "response": {
      "focus_school": {
        "school_id": 1,
        "school_name": "Focus School Academy",
        "results": {
          "1": {
            "suppressed": false,
            "suppression_message": null,
            "results": [
              {
                "mean": 74.8,
                "student_n": 60
              }
            ]
          },
          "2": {
            "suppressed": false,
            "suppression_message": null,
            "results": [
              {
                "mean": 77.3,
                "student_n": 63
              }
            ]
          }
        }
      },
      "neighbors": [
        {
          "school_id": 2,
          "school_name": "Neighbouring School",
          "results": {
            "1": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "mean": 70.7,
                  "student_n": 55
                }
              ]
            },
            "2": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "mean": 73.4,
                  "student_n": 57
                }
              ]
            }
          }
        }
      ],
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {
        "d_sex": [
          "F"
        ]
      }
    }
  },
  {
    "id": "query.group-by-sex",
    "method": "POST",
    "path": "/api/query",
    "status": 200,
    "request_model": "QueryRequest",
    "response_model": "QueryResponse",
    "request": {
      "school_id": 1,
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [
        "d_sex"
      ],
      "filters": {},
      "include_neighbors": true
    },
    "response": {
      "focus_school": {
        "school_id": 1,
        "school_name": "Focus School Academy",
        "results": {
          "1": {
            "suppressed": false,
            "suppression_message": null,
            "results": [
              {
                "d_sex": "M",
                "mean": 76.2,
                "student_n": 60
              },
              {
                "d_sex": "F",
                "mean": 74.8,
                "student_n": 60
              }
            ]
          },
          "2": {
            "suppressed": false,
            "suppression_message": null,
            "results": [
              {
                "d_sex": "M",
                "mean": 79.1,
                "student_n": 62
              },
              {
                "d_sex": "F",
                "mean": 77.3,
                "student_n": 63
              }
            ]
          }
        }
      },
      "neighbors": [
        {
          "school_id": 2,
          "school_name": "Neighbouring School",
          "results": {
            "1": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "d_sex": "M",
                  "mean": 73.5,
                  "student_n": 55
                },
                {
                  "d_sex": "F",
                  "mean": 70.7,
                  "student_n": 55
                }
              ]
            },
            "2": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "d_sex": "M",
                  "mean": 76.2,
                  "student_n": 58
                },
                {
                  "d_sex": "F",
                  "mean": 73.4,
                  "student_n": 57
                }
              ]
            }
          }
        }
      ],
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [
        "d_sex"
      ],
      "filters": {}
    }
  },
  {
    "id": "query.school-2",
    "method": "POST",
    "path": "/api/query",
    "status": 200,
    "request_model": "QueryRequest",
    "response_model": "QueryResponse",
    "request": {
      "school_id": 2,
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {},
      "include_neighbors": true
    },
    "response": {
      "focus_school": {
        "school_id": 2,
        "school_name": "Neighbouring School",
        "results": {
          "1": {
            "suppressed": false,
            "suppression_message": null,
            "results": [
              {
                "mean": 72.1,
                "student_n": 110
              }
            ]
          },
          "2": {
            "suppressed": false,
            "suppression_message": null,
            "results": [
              {
                "mean": 74.8,
                "student_n": 115
              }
            ]
          }
        }
      },
      "neighbors": [
        {
          "school_id": 1,
          "school_name": "Focus School Academy",
          "results": {
            "1": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "mean": 75.5,
                  "student_n": 120
                }
              ]
            },
            "2": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "mean": 78.2,
                  "student_n": 125
                }
              ]
            }
          }
        }
      ],
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {}
    }
  },
  {
    "id": "query.suppressed-focus",
    "method": "POST",
    "path": "/api/query",
    "status": 200,
    "request_model": "QueryRequest",
    "response_model": "QueryResponse",
    "request": {
      "school_id": 1,
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {},
      "include_neighbors": true
    },
    "response": {
      "focus_school": {
        "school_id": 1,
        "school_name": "Focus School Academy",
        "results": {
          "1": {
            "suppressed": true,
            "suppression_message": "Results suppressed due to small sample size (n < 10)",
            "results": null
          },
          "2": {
            "suppressed": true,
            "suppression_message": "Results suppressed due to small sample size (n < 10)",
            "results": null
          }
        }
      },
      "neighbors": [
        {
          "school_id": 2,
          "school_name": "Neighbouring School",
          "results": {
            "1": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "mean": 72.1,
                  "student_n": 110
                }
              ]
            },
            "2": {
              "suppressed": false,
              "suppression_message": null,
              "results": [
                {
                  "mean": 74.8,
                  "student_n": 115
                }
              ]
            }
          }
        }
      ],
      "variable": "score",
      "waves": [
        "1",
        "2"
      ],
      "aggregations": [],
      "filters": {}
    }
  },
  {
    "id": "schools.admin-all",
    "method": "GET",
    "path": "/schools",
    "status": 200,
    "request_model": null,
    "response_model": "SchoolListResponse",
    "request": null,
    "response": [
      {
        "id": 1,
        "name": "Focus School Academy",
        "size": "medium",
        "category": "comprehensive",
        "geographical_neighbor_ids": [
          2
        ],
        "statistical_neighbor_ids": [
          2,
          3
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1",
            "2"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B",
                "C"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "Black",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "7"
              ],
              "scope": "shared"
            }
          ]
        }
      },
      {
        "id": 2,
        "name": "Neighbouring School",
        "size": "large",
        "category": "academy",
        "geographical_neighbor_ids": [
          1
        ],
        "statistical_neighbor_ids": [
          1,
          3
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B",
                "C"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "Black",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "8"
              ],
              "scope": "shared"
            }
          ]
        }
      },
      {
        "id": 3,
        "name": "State Local High",
        "size": "small",
        "category": "grammar",
        "geographical_neighbor_ids": [],
        "statistical_neighbor_ids": [
          1,
          2
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "7"
              ],
              "scope": "shared"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "schools.empty",
    "method": "GET",
    "path": "/schools",
    "status": 200,
    "request_model": null,
    "response_model": "SchoolListResponse",
    "request": null,
    "response": []
  },
  {
    "id": "schools.user-default",
    "method": "GET",
    "path": "/schools",
    "status": 200,
    "request_model": null,
    "response_model": "SchoolListResponse",
    "request": null,
    "response": [
      {
        "id": 1,
        "name": "Focus School Academy",
        "size": "medium",
        "category": "comprehensive",
        "geographical_neighbor_ids": [
          2
        ],
        "statistical_neighbor_ids": [
          2,
          3
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1",
            "2"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B",
                "C"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "Black",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "7"
              ],
              "scope": "shared"
            }
          ]
        }
      },
      {
        "id": 2,
        "name": "Neighbouring School",
        "size": "large",
        "category": "academy",
        "geographical_neighbor_ids": [
          1
        ],
        "statistical_neighbor_ids": [
          1
        ],
        "query_options": {
          "variables": [
            "bw_wbeing_1",
            "bw_wbeing_2",
            "bw_wbeing_3",
            "bw_wbeing_total"
          ],
          "waves": [
            "1"
          ],
          "aggregations": [
            {
              "value": "class",
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "scope": "shared"
            }
          ],
          "filters": [
            {
              "value": "class",
              "values": [
                "A",
                "B",
                "C"
              ],
              "scope": "focus_only"
            },
            {
              "value": "d_ethnicity",
              "values": [
                "Asian",
                "Black",
                "White"
              ],
              "scope": "shared"
            },
            {
              "value": "d_sex",
              "values": [
                "F",
                "M"
              ],
              "scope": "shared"
            },
            {
              "value": "yearGroup",
              "values": [
                "8"
              ],
              "scope": "shared"
            }
          ]
        }
      }
    ]
  }
] as const;
