#!/usr/bin/env python3
"""Transform a clean wide mock dataset into messy per-form seed CSVs.

This script takes the canonical 3-wave wide CSV generated by glow-dummies and
deterministically transforms it into separate form-specific CSVs plus a manifest
describing the intended historical collection patterns.

The transformation is deliberately repeatable and documented:

- schools are assigned fixed 5-year wave patterns
- BeeWell v1/v2 usage is assigned deterministically by school and period
- PHQ-9 coverage is intentionally patchy
- some students join late, leave early, or disappear entirely
- a small number of synthetic late joiners are introduced from donor rows
- some students repeat or skip a year group
- some form submissions are missing even when the school uses that form
- intended createdAt timestamps are assigned per submission for later ODK
  timestamp rewriting
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


PERIOD_BY_WAVE = {
    1: "2020-2021",
    2: "2021-2022",
    3: "2022-2023",
    4: "2023-2024",
    5: "2024-2025",
}

MIDYEAR_CREATED_AT = {
    1: "2021-02-15T12:00:00Z",
    2: "2022-02-15T12:00:00Z",
    3: "2023-02-15T12:00:00Z",
    4: "2024-02-15T12:00:00Z",
    5: "2025-02-15T12:00:00Z",
}

BOUNDARY_CREATED_AT = {
    1: ("2020-09-01T12:00:00Z", "2021-08-31T12:00:00Z"),
    2: ("2021-09-01T12:00:00Z", "2022-08-31T12:00:00Z"),
    3: ("2022-09-01T12:00:00Z", "2023-08-31T12:00:00Z"),
    4: ("2023-09-01T12:00:00Z", "2024-08-31T12:00:00Z"),
    5: ("2024-09-01T12:00:00Z", "2025-08-31T12:00:00Z"),
}

PHQ_COLLISION_SOURCE_FIELD = "phq_overlap_bw_wbeing_1"
HELPER_FIELDS = [
    "instance_id",
    "wave",
    "period_id",
    "form_version",
    "target_created_at",
    "boundary_case",
]


@dataclass(frozen=True)
class SchoolPlan:
    school: str
    school_code: str
    target_waves: tuple[int, ...]
    phq_mode: str
    wave_mappings: tuple[tuple[str, int, int], ...]
    all_v1: bool = False
    middle_only_v1: bool = False
    mixed_wave: int | None = None
    donor_only: bool = False


def stable_int(*parts: object) -> int:
    text = "||".join(str(part) for part in parts)
    digest = hashlib.sha256(text.encode("utf-8")).digest()
    return int.from_bytes(digest[:8], "big")


def build_instance_id(uid: str, form_id: str, period_id: str) -> str:
    digest = hashlib.sha256(f"{uid}||{form_id}||{period_id}".encode("utf-8")).hexdigest()[:32]
    return f"uuid:{digest}"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    return slug or "school"


def parse_form_fields(form_path: Path) -> list[str]:
    root = ET.parse(form_path).getroot()
    data = root.find(".//{*}instance/{*}data")
    if data is None:
        raise ValueError(f"No <data> instance found in {form_path}")

    fields: list[str] = []
    for child in data:
        tag = child.tag.split("}")[-1]
        if tag == "meta":
            continue
        fields.append(tag)
    return fields


def read_csv_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def as_int(value: str) -> int | None:
    if value is None or value == "":
        return None
    return int(float(value))


def from_int(value: int | None) -> str:
    return "" if value is None else str(value)


def shift_value(value: str, delta: int) -> str:
    parsed = as_int(value)
    return from_int(None if parsed is None else parsed + delta)


def rescale_value(value: str, old_max: int, new_max: int) -> str:
    parsed = as_int(value)
    if parsed is None:
        return ""
    if old_max == 0:
        return from_int(0)
    return from_int(round(parsed * new_max / old_max))


def choose_created_at(uid: str, form_id: str, target_wave: int) -> tuple[str, bool]:
    if stable_int("boundary_created_at", uid, form_id, target_wave) % 53 == 0:
        edge_index = stable_int("boundary_side", uid, form_id, target_wave) % 2
        return BOUNDARY_CREATED_AT[target_wave][edge_index], True
    return MIDYEAR_CREATED_AT[target_wave], False


def assign_school_plans(schools: list[str]) -> dict[str, SchoolPlan]:
    if len(schools) < 20:
        raise ValueError(
            f"Expected at least 20 schools in the canonical base dataset; found {len(schools)}"
        )

    donor_four_wave_school = schools[-2]
    donor_five_wave_school = schools[-1]
    output_schools = schools[:-2]

    pattern_sequence: list[tuple[int, ...]] = (
        [(1, 2, 3)] * 5
        + [(2, 3, 4)] * 5
        + [(3, 4, 5)] * 4
        + [(1, 2, 5)] * 1
        + [(1, 3, 5)] * 1
        + [(1, 2, 3, 4)] * 1
        + [(1, 2, 3, 4, 5)] * 1
    )
    phq_modes = ["all", "first_two", "last_two", "middle_only", "none"]

    plans: dict[str, SchoolPlan] = {}
    for school in (donor_four_wave_school, donor_five_wave_school):
        donor_index = schools.index(school)
        plans[school] = SchoolPlan(
            school=school,
            school_code=f"sch{donor_index + 1:02d}_{slugify(school)}",
            target_waves=(),
            phq_mode="none",
            wave_mappings=(),
            donor_only=True,
        )

    for index, school in enumerate(output_schools):
        pattern = pattern_sequence[index % len(pattern_sequence)]
        wave_mappings = tuple((school, source_wave, target_wave) for source_wave, target_wave in zip((1, 2, 3), pattern[:3], strict=True))

        if pattern == (1, 2, 3, 4):
            wave_mappings = wave_mappings + ((donor_four_wave_school, 1, 4),)
        elif pattern == (1, 2, 3, 4, 5):
            wave_mappings = wave_mappings + (
                (donor_five_wave_school, 1, 4),
                (donor_five_wave_school, 2, 5),
            )

        plan = SchoolPlan(
            school=school,
            school_code=f"sch{index + 1:02d}_{slugify(school)}",
            target_waves=pattern,
            phq_mode=phq_modes[index % len(phq_modes)],
            wave_mappings=wave_mappings,
            all_v1=index == 0,
            middle_only_v1=index == 1,
            mixed_wave=pattern[0] if index == 2 else None,
        )
        plans[school] = plan
    return plans


def keep_source_wave(school: str, uid: str, source_wave: int) -> bool:
    drop_all = stable_int("drop_all", school, uid) % 97 == 0
    if drop_all:
        return False

    if stable_int("late_join", school, uid) % 17 == 0 and source_wave == 1:
        return False
    if stable_int("early_leave", school, uid) % 19 == 0 and source_wave == 3:
        return False
    if stable_int("mid_gap", school, uid) % 29 == 0 and source_wave == 2:
        return False
    return True


def adjusted_year_group(uid: str, source_row: dict[str, str], source_wave: int) -> str:
    base = as_int(source_row.get("yearGroup", ""))
    if base is None:
        return ""

    adjusted = base
    if source_wave >= 2 and stable_int("repeat_year_group", uid) % 37 == 0:
        adjusted -= 1
    elif source_wave >= 2 and stable_int("skip_year_group", uid) % 41 == 0:
        adjusted += 1

    return from_int(max(1, adjusted))


def bewell_version(plan: SchoolPlan, target_wave: int, uid: str) -> str:
    if plan.all_v1:
        return "1"
    if plan.middle_only_v1:
        return "1" if target_wave == plan.target_waves[len(plan.target_waves) // 2] else "2"
    if plan.mixed_wave == target_wave:
        return "1" if stable_int("mixed_v1_v2", uid, target_wave) % 10 < 7 else "2"
    if target_wave == 1:
        return "1"
    return "2"


def phq_collected(plan: SchoolPlan, target_wave: int) -> bool:
    if plan.phq_mode == "all":
        return True
    if plan.phq_mode == "first_two":
        return target_wave in set(plan.target_waves[:2])
    if plan.phq_mode == "last_two":
        return target_wave in set(plan.target_waves[-2:])
    if plan.phq_mode == "middle_only":
        return target_wave == plan.target_waves[len(plan.target_waves) // 2]
    return False


def synthetic_joiners(student_map: dict[str, dict[int, dict[str, str]]]) -> dict[str, dict[int, dict[str, str]]]:
    generated: dict[str, dict[int, dict[str, str]]] = {}
    donor_uids = sorted(student_map)
    for join_source_wave, count in ((2, 2), (3, 1)):
        donors = [
            uid for uid in donor_uids
            if join_source_wave in student_map[uid]
        ]
        donors.sort(key=lambda uid: (stable_int("joiner_rank", uid, join_source_wave), uid))
        for ordinal, donor_uid in enumerate(donors[:count], start=1):
            new_uid = f"joiner_{join_source_wave}_{ordinal:02d}_{donor_uid}"
            generated[new_uid] = {
                source_wave: dict(student_map[donor_uid][source_wave])
                for source_wave in sorted(student_map[donor_uid])
                if source_wave >= join_source_wave
            }
    return generated


def build_form_record(fields: Iterable[str], row: dict[str, str], uid: str, school: str) -> dict[str, str]:
    record = {field: row.get(field, "") for field in fields}
    record["uid"] = uid
    record["school"] = school
    return record


def build_bewell_v1_record(fields: Iterable[str], row: dict[str, str], uid: str, school: str) -> dict[str, str]:
    record = build_form_record(fields, row, uid, school)
    for field in list(record):
        if field.startswith("bw_wbeing_"):
            record[field] = shift_value(record[field], 1)
        elif field.startswith("bw_stress_"):
            record[field] = rescale_value(record[field], old_max=4, new_max=3)
    return record


def build_phq_record(fields: Iterable[str], row: dict[str, str], uid: str, school: str) -> dict[str, str]:
    record = {field: "" for field in fields}
    record["uid"] = uid
    record["school"] = school
    for field in fields:
        if field in {"uid", "school"}:
            continue
        if field == "bw_wbeing_1":
            record[field] = row.get(PHQ_COLLISION_SOURCE_FIELD, "")
        else:
            record[field] = row.get(field, "")
    return record


def build_demographics_record(fields: Iterable[str], row: dict[str, str], uid: str, school: str, source_wave: int) -> dict[str, str]:
    record = build_form_record(fields, row, uid, school)
    record["yearGroup"] = adjusted_year_group(uid, row, source_wave)
    return record


def main() -> None:
    parser = argparse.ArgumentParser(description="Transform canonical mock data into messy per-form CSVs")
    parser.add_argument("--input", type=Path, required=True, help="Canonical wide CSV from glow-dummies")
    parser.add_argument("--output-dir", type=Path, required=True, help="Directory to write transformed CSVs and manifest")
    parser.add_argument("--forms-dir", type=Path, default=Path("odk-forms"), help="Directory containing ODK form XMLs")
    args = parser.parse_args()

    rows = read_csv_rows(args.input)
    schools = sorted({row["school"] for row in rows})
    plans = assign_school_plans(schools)

    forms_dir = args.forms_dir
    bewell_v1_fields = parse_form_fields(forms_dir / "bewell_questionnaire_v1.xml")
    bewell_v2_fields = parse_form_fields(forms_dir / "bewell_questionnaire_v2.xml")
    phq_fields = parse_form_fields(forms_dir / "phq9_questionnaire.xml")
    demographics_fields = parse_form_fields(forms_dir / "demographics_questionnaire.xml")

    # Build school -> uid -> wave -> row mapping.
    school_students: dict[str, dict[str, dict[int, dict[str, str]]]] = {}
    for row in rows:
        school = row["school"]
        uid = row["uid"]
        wave = int(row["wave"])
        school_students.setdefault(school, {}).setdefault(uid, {})[wave] = row

    bewell_v1_rows: list[dict[str, str]] = []
    bewell_v2_rows: list[dict[str, str]] = []
    phq_rows: list[dict[str, str]] = []
    demographics_rows: list[dict[str, str]] = []
    manifest_rows: list[dict[str, str]] = []
    school_plan_rows: list[dict[str, str]] = []

    for school in schools:
        plan = plans[school]
        school_plan_rows.append(
            {
                "school": plan.school,
                "school_code": plan.school_code,
                "target_waves": ",".join(str(w) for w in plan.target_waves),
                "phq_mode": plan.phq_mode,
                "all_v1": str(plan.all_v1).lower(),
                "middle_only_v1": str(plan.middle_only_v1).lower(),
                "mixed_wave": "" if plan.mixed_wave is None else str(plan.mixed_wave),
                "donor_only": str(plan.donor_only).lower(),
                "wave_mappings": ";".join(
                    f"{source_school}:{source_wave}->{target_wave}"
                    for source_school, source_wave, target_wave in plan.wave_mappings
                ),
            }
        )

        if plan.donor_only:
            continue

        school_map = {uid: dict(waves) for uid, waves in school_students[school].items()}
        school_map.update(synthetic_joiners(school_map))

        base_uids = sorted(school_map)
        for base_uid in base_uids:
            prefixed_uid = f"{plan.school_code}_{base_uid}"
            base_wave_rows = school_map[base_uid]

            for source_school, source_wave, target_wave in plan.wave_mappings:
                if source_school == school:
                    source_rows = base_wave_rows
                else:
                    donor_map = school_students[source_school]
                    donor_uids = sorted(donor_map)
                    donor_uid = donor_uids[stable_int("donor_uid_pick", school, base_uid, source_school) % len(donor_uids)]
                    source_rows = donor_map[donor_uid]

                if source_wave not in source_rows:
                    continue
                if source_school == school and not keep_source_wave(school, prefixed_uid, source_wave):
                    continue

                source_row = source_rows[source_wave]
                period_id = PERIOD_BY_WAVE[target_wave]

                version = bewell_version(plan, target_wave, prefixed_uid)
                created_at, boundary_case = choose_created_at(prefixed_uid, "bewell_questionnaire", target_wave)
                instance_id = build_instance_id(prefixed_uid, "bewell_questionnaire", period_id)
                helper_values = {
                    "instance_id": instance_id,
                    "wave": str(target_wave),
                    "period_id": period_id,
                    "form_version": version,
                    "target_created_at": created_at,
                    "boundary_case": str(boundary_case).lower(),
                }

                if version == "1":
                    bewell_v1_rows.append(helper_values | build_bewell_v1_record(bewell_v1_fields, source_row, prefixed_uid, school))
                else:
                    bewell_v2_rows.append(helper_values | build_form_record(bewell_v2_fields, source_row, prefixed_uid, school))

                manifest_rows.append(
                    {
                        "instance_id": instance_id,
                        "uid": prefixed_uid,
                        "school": school,
                        "form_id": "bewell_questionnaire",
                        "form_version": version,
                        "source_wave": str(source_wave),
                        "target_wave": str(target_wave),
                        "target_period_id": period_id,
                        "target_created_at": created_at,
                        "boundary_case": str(boundary_case).lower(),
                        "csv_file": f"bewell_questionnaire_v{version}.csv",
                    }
                )

                if phq_collected(plan, target_wave) and stable_int("missing_phq", prefixed_uid, target_wave) % 13 != 0:
                    created_at, boundary_case = choose_created_at(prefixed_uid, "phq9_questionnaire", target_wave)
                    phq_rows.append(
                        {
                            "instance_id": build_instance_id(prefixed_uid, "phq9_questionnaire", period_id),
                            "wave": str(target_wave),
                            "period_id": period_id,
                            "form_version": "1",
                            "target_created_at": created_at,
                            "boundary_case": str(boundary_case).lower(),
                        }
                        | build_phq_record(phq_fields, source_row, prefixed_uid, school)
                    )
                    manifest_rows.append(
                        {
                            "instance_id": build_instance_id(prefixed_uid, "phq9_questionnaire", period_id),
                            "uid": prefixed_uid,
                            "school": school,
                            "form_id": "phq9_questionnaire",
                            "form_version": "1",
                            "source_wave": str(source_wave),
                            "target_wave": str(target_wave),
                            "target_period_id": period_id,
                            "target_created_at": created_at,
                            "boundary_case": str(boundary_case).lower(),
                            "csv_file": "phq9_questionnaire.csv",
                        }
                    )

                if stable_int("missing_demographics", prefixed_uid, target_wave) % 17 != 0:
                    created_at, boundary_case = choose_created_at(prefixed_uid, "demographics_questionnaire", target_wave)
                    demographics_rows.append(
                        {
                            "instance_id": build_instance_id(prefixed_uid, "demographics_questionnaire", period_id),
                            "wave": str(target_wave),
                            "period_id": period_id,
                            "form_version": "1",
                            "target_created_at": created_at,
                            "boundary_case": str(boundary_case).lower(),
                        }
                        | build_demographics_record(
                            demographics_fields,
                            source_row,
                            prefixed_uid,
                            school,
                            source_wave,
                        )
                    )
                    manifest_rows.append(
                        {
                            "instance_id": build_instance_id(prefixed_uid, "demographics_questionnaire", period_id),
                            "uid": prefixed_uid,
                            "school": school,
                            "form_id": "demographics_questionnaire",
                            "form_version": "1",
                            "source_wave": str(source_wave),
                            "target_wave": str(target_wave),
                            "target_period_id": period_id,
                            "target_created_at": created_at,
                            "boundary_case": str(boundary_case).lower(),
                            "csv_file": "demographics_questionnaire.csv",
                        }
                    )

    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    write_csv(output_dir / "bewell_questionnaire_v1.csv", bewell_v1_rows, HELPER_FIELDS + bewell_v1_fields)
    write_csv(output_dir / "bewell_questionnaire_v2.csv", bewell_v2_rows, HELPER_FIELDS + bewell_v2_fields)
    write_csv(output_dir / "phq9_questionnaire.csv", phq_rows, HELPER_FIELDS + phq_fields)
    write_csv(output_dir / "demographics_questionnaire.csv", demographics_rows, HELPER_FIELDS + demographics_fields)
    write_csv(
        output_dir / "manifest.csv",
        manifest_rows,
        [
            "instance_id",
            "uid",
            "school",
            "form_id",
            "form_version",
            "source_wave",
            "target_wave",
            "target_period_id",
            "target_created_at",
            "boundary_case",
            "csv_file",
        ],
    )
    write_csv(
        output_dir / "school_plans.csv",
        school_plan_rows,
        [
            "school",
            "school_code",
            "target_waves",
            "phq_mode",
            "all_v1",
            "middle_only_v1",
            "mixed_wave",
            "donor_only",
            "wave_mappings",
        ],
    )

    summary = {
        "input_csv": str(args.input),
        "base_school_count": len(schools),
        "output_school_count": sum(1 for plan in plans.values() if not plan.donor_only),
        "donor_school_count": sum(1 for plan in plans.values() if plan.donor_only),
        "bewell_v1_submissions": len(bewell_v1_rows),
        "bewell_v2_submissions": len(bewell_v2_rows),
        "phq9_submissions": len(phq_rows),
        "demographics_submissions": len(demographics_rows),
        "manifest_rows": len(manifest_rows),
        "plans": [asdict(plans[school]) for school in schools],
    }
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
